# 5 Pandas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df1 = pd.Series([1, 2, 3, 4, np.nan, 5, 6])

In [6]:
df1

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    5.0
6    6.0
dtype: float64

# DateTime

`pd.date_range`function get value in format **YYYY-MM-DD** and in **string format**

In [15]:
df2 = pd.date_range('20220129', periods=6)

df2

DatetimeIndex(['2022-01-29', '2022-01-30', '2022-01-31', '2022-02-01',
               '2022-02-02', '2022-02-03'],
              dtype='datetime64[ns]', freq='D')

**OR**

In [18]:
df4 = pd.date_range(start='20220129', end='20220203')

df4

DatetimeIndex(['2022-01-29', '2022-01-30', '2022-01-31', '2022-02-01',
               '2022-02-02', '2022-02-03'],
              dtype='datetime64[ns]', freq='D')

In [21]:
# wrong declaration
df3 = pd.date_range(20220129, periods=6)

df3

DatetimeIndex(['1970-01-01 00:00:00.020220129',
               '1970-01-02 00:00:00.020220129',
               '1970-01-03 00:00:00.020220129',
               '1970-01-04 00:00:00.020220129',
               '1970-01-05 00:00:00.020220129',
               '1970-01-06 00:00:00.020220129'],
              dtype='datetime64[ns]', freq='D')

In [24]:
df5 = pd.DataFrame(np.random.randn(6,4), index=df2, columns= list('ABCD'))

df5

                   A         B         C         D
2022-01-29  1.621576 -0.936206  1.010117  1.223335
2022-01-30 -0.167754  0.582021  1.200568 -0.664181
2022-01-31 -0.743690 -0.518799 -0.415181 -0.669618
2022-02-01 -0.058327  0.996531  0.849046  1.673973
2022-02-02 -0.220250 -0.962641  0.076240  0.136025
2022-02-03  0.268471  0.555794 -1.005842 -1.004181

Creating dataframe of random numbers in 6 by 4 matrix, index is given as df2 which contains 6 dates, column name is given as A, B, C, D

In [48]:
df6 = pd.DataFrame({'A': 1,
                   'B': pd.Timestamp('20220101'),
                   'C': pd.Series(1, index=list(range(4)), dtype=float),
                   'D': np.array([3] * len(df6), dtype=int ),
                   'E': pd.Categorical(['Test', 'Train', 'View', 'Final']),
                   'F': 'Foo'})

df6

   A          B    C  D      E    F
0  1 2022-01-01  1.0  3   Test  Foo
1  1 2022-01-01  1.0  3  Train  Foo
2  1 2022-01-01  1.0  3   View  Foo
3  1 2022-01-01  1.0  3  Final  Foo

In [46]:
df6.dtypes

A           float64
B    datetime64[ns]
C           float64
D             int32
E          category
F            object
dtype: object